name: clang-scan

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ci-clang-scan
    if: ${{ github.repository != 'opcm/pcm' }}    

    steps:
    - uses: actions/checkout@v2
    - name: scan-build
      run: scan-build --exclude simdjson --status-bugs make -j
