name: g++ 4.8 build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ci-gcc48

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        g++ --version
        make install prefix=. -j

