name: g++ 9 build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ci-gcc9

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        g++ --version
        make install prefix=. -j
