name: g++ 5 build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ci-gcc5
    if: ${{ github.repository != 'opcm/pcm' }}        

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        g++ --version
        git clone https://github.com/simdjson/simdjson.git
        make install prefix=. -j
